// Copyright 2017 The go-paystack AUTHORS. All rights reserved.
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by gen-accessors; DO NOT EDIT.

package paystack

import (
	"time"
)

// GetAccountName returns the AccountName field if it's non-nil, zero value otherwise.
func (a *AccountData) GetAccountName() string {
	if a == nil || a.AccountName == nil {
		return ""
	}
	return *a.AccountName
}

// GetAccountNumber returns the AccountNumber field if it's non-nil, zero value otherwise.
func (a *AccountData) GetAccountNumber() string {
	if a == nil || a.AccountNumber == nil {
		return ""
	}
	return *a.AccountNumber
}

// GetAuthorizationCode returns the AuthorizationCode field if it's non-nil, zero value otherwise.
func (a *Authorization) GetAuthorizationCode() string {
	if a == nil || a.AuthorizationCode == nil {
		return ""
	}
	return *a.AuthorizationCode
}

// GetBank returns the Bank field if it's non-nil, zero value otherwise.
func (a *Authorization) GetBank() string {
	if a == nil || a.Bank == nil {
		return ""
	}
	return *a.Bank
}

// GetBin returns the Bin field if it's non-nil, zero value otherwise.
func (a *Authorization) GetBin() string {
	if a == nil || a.Bin == nil {
		return ""
	}
	return *a.Bin
}

// GetCardType returns the CardType field if it's non-nil, zero value otherwise.
func (a *Authorization) GetCardType() string {
	if a == nil || a.CardType == nil {
		return ""
	}
	return *a.CardType
}

// GetChannel returns the Channel field if it's non-nil, zero value otherwise.
func (a *Authorization) GetChannel() string {
	if a == nil || a.Channel == nil {
		return ""
	}
	return *a.Channel
}

// GetCountryCode returns the CountryCode field if it's non-nil, zero value otherwise.
func (a *Authorization) GetCountryCode() string {
	if a == nil || a.CountryCode == nil {
		return ""
	}
	return *a.CountryCode
}

// GetCustomer returns the Customer field if it's non-nil, zero value otherwise.
func (a *Authorization) GetCustomer() string {
	if a == nil || a.Customer == nil {
		return ""
	}
	return *a.Customer
}

// GetExpMonth returns the ExpMonth field if it's non-nil, zero value otherwise.
func (a *Authorization) GetExpMonth() string {
	if a == nil || a.ExpMonth == nil {
		return ""
	}
	return *a.ExpMonth
}

// GetExpYear returns the ExpYear field if it's non-nil, zero value otherwise.
func (a *Authorization) GetExpYear() string {
	if a == nil || a.ExpYear == nil {
		return ""
	}
	return *a.ExpYear
}

// GetLast4 returns the Last4 field if it's non-nil, zero value otherwise.
func (a *Authorization) GetLast4() string {
	if a == nil || a.Last4 == nil {
		return ""
	}
	return *a.Last4
}

// GetReusable returns the Reusable field if it's non-nil, zero value otherwise.
func (a *Authorization) GetReusable() bool {
	if a == nil || a.Reusable == nil {
		return false
	}
	return *a.Reusable
}

// GetSignature returns the Signature field if it's non-nil, zero value otherwise.
func (a *Authorization) GetSignature() string {
	if a == nil || a.Signature == nil {
		return ""
	}
	return *a.Signature
}

// GetBalance returns the Balance field if it's non-nil, zero value otherwise.
func (b *Balance) GetBalance() int {
	if b == nil || b.Balance == nil {
		return 0
	}
	return *b.Balance
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (b *Balance) GetCurrency() string {
	if b == nil || b.Currency == nil {
		return ""
	}
	return *b.Currency
}

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (b *Bank) GetActive() bool {
	if b == nil || b.Active == nil {
		return false
	}
	return *b.Active
}

// GetCode returns the Code field if it's non-nil, zero value otherwise.
func (b *Bank) GetCode() string {
	if b == nil || b.Code == nil {
		return ""
	}
	return *b.Code
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (b *Bank) GetCreatedAt() time.Time {
	if b == nil || b.CreatedAt == nil {
		return time.Time{}
	}
	return *b.CreatedAt
}

// GetGateway returns the Gateway field if it's non-nil, zero value otherwise.
func (b *Bank) GetGateway() string {
	if b == nil || b.Gateway == nil {
		return ""
	}
	return *b.Gateway
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (b *Bank) GetId() int {
	if b == nil || b.Id == nil {
		return 0
	}
	return *b.Id
}

// GetLongcode returns the Longcode field if it's non-nil, zero value otherwise.
func (b *Bank) GetLongcode() string {
	if b == nil || b.Longcode == nil {
		return ""
	}
	return *b.Longcode
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (b *Bank) GetName() string {
	if b == nil || b.Name == nil {
		return ""
	}
	return *b.Name
}

// GetSlug returns the Slug field if it's non-nil, zero value otherwise.
func (b *Bank) GetSlug() string {
	if b == nil || b.Slug == nil {
		return ""
	}
	return *b.Slug
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (b *Bank) GetUpdatedAt() time.Time {
	if b == nil || b.UpdatedAt == nil {
		return time.Time{}
	}
	return *b.UpdatedAt
}

// GetBank returns the Bank field if it's non-nil, zero value otherwise.
func (b *Bin) GetBank() string {
	if b == nil || b.Bank == nil {
		return ""
	}
	return *b.Bank
}

// GetBin returns the Bin field if it's non-nil, zero value otherwise.
func (b *Bin) GetBin() string {
	if b == nil || b.Bin == nil {
		return ""
	}
	return *b.Bin
}

// GetBrand returns the Brand field if it's non-nil, zero value otherwise.
func (b *Bin) GetBrand() string {
	if b == nil || b.Brand == nil {
		return ""
	}
	return *b.Brand
}

// GetCardType returns the CardType field if it's non-nil, zero value otherwise.
func (b *Bin) GetCardType() string {
	if b == nil || b.CardType == nil {
		return ""
	}
	return *b.CardType
}

// GetCountryCode returns the CountryCode field if it's non-nil, zero value otherwise.
func (b *Bin) GetCountryCode() string {
	if b == nil || b.CountryCode == nil {
		return ""
	}
	return *b.CountryCode
}

// GetCountryName returns the CountryName field if it's non-nil, zero value otherwise.
func (b *Bin) GetCountryName() string {
	if b == nil || b.CountryName == nil {
		return ""
	}
	return *b.CountryName
}

// GetLinkedBankId returns the LinkedBankId field if it's non-nil, zero value otherwise.
func (b *Bin) GetLinkedBankId() int {
	if b == nil || b.LinkedBankId == nil {
		return 0
	}
	return *b.LinkedBankId
}

// GetSubBrand returns the SubBrand field if it's non-nil, zero value otherwise.
func (b *Bin) GetSubBrand() string {
	if b == nil || b.SubBrand == nil {
		return ""
	}
	return *b.SubBrand
}

// GetBirthday returns the Birthday field if it's non-nil, zero value otherwise.
func (b *BirthdayRequest) GetBirthday() string {
	if b == nil || b.Birthday == nil {
		return ""
	}
	return *b.Birthday
}

// GetReference returns the Reference field if it's non-nil, zero value otherwise.
func (b *BirthdayRequest) GetReference() string {
	if b == nil || b.Reference == nil {
		return ""
	}
	return *b.Reference
}

// GetBatchCode returns the BatchCode field if it's non-nil, zero value otherwise.
func (b *BulkBatch) GetBatchCode() string {
	if b == nil || b.BatchCode == nil {
		return ""
	}
	return *b.BatchCode
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (b *BulkBatch) GetCreatedAt() time.Time {
	if b == nil || b.CreatedAt == nil {
		return time.Time{}
	}
	return *b.CreatedAt
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (b *BulkBatch) GetDomain() string {
	if b == nil || b.Domain == nil {
		return ""
	}
	return *b.Domain
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (b *BulkBatch) GetId() int {
	if b == nil || b.Id == nil {
		return 0
	}
	return *b.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (b *BulkBatch) GetIntegration() int {
	if b == nil || b.Integration == nil {
		return 0
	}
	return *b.Integration
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (b *BulkBatch) GetStatus() bool {
	if b == nil || b.Status == nil {
		return false
	}
	return *b.Status
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (b *BulkBatch) GetUpdatedAt() time.Time {
	if b == nil || b.UpdatedAt == nil {
		return time.Time{}
	}
	return *b.UpdatedAt
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (b *BulkBatchRequest) GetAmount() int {
	if b == nil || b.Amount == nil {
		return 0
	}
	return *b.Amount
}

// GetAuthorization returns the Authorization field if it's non-nil, zero value otherwise.
func (b *BulkBatchRequest) GetAuthorization() string {
	if b == nil || b.Authorization == nil {
		return ""
	}
	return *b.Authorization
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (b *BulkCharge) GetAmount() int {
	if b == nil || b.Amount == nil {
		return 0
	}
	return *b.Amount
}

// GetBulkcharge returns the Bulkcharge field if it's non-nil, zero value otherwise.
func (b *BulkCharge) GetBulkcharge() int {
	if b == nil || b.Bulkcharge == nil {
		return 0
	}
	return *b.Bulkcharge
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (b *BulkCharge) GetCreatedAt() time.Time {
	if b == nil || b.CreatedAt == nil {
		return time.Time{}
	}
	return *b.CreatedAt
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (b *BulkCharge) GetCurrency() string {
	if b == nil || b.Currency == nil {
		return ""
	}
	return *b.Currency
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (b *BulkCharge) GetDomain() string {
	if b == nil || b.Domain == nil {
		return ""
	}
	return *b.Domain
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (b *BulkCharge) GetId() int {
	if b == nil || b.Id == nil {
		return 0
	}
	return *b.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (b *BulkCharge) GetIntegration() int {
	if b == nil || b.Integration == nil {
		return 0
	}
	return *b.Integration
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (b *BulkCharge) GetStatus() string {
	if b == nil || b.Status == nil {
		return ""
	}
	return *b.Status
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (b *BulkCharge) GetUpdatedAt() time.Time {
	if b == nil || b.UpdatedAt == nil {
		return time.Time{}
	}
	return *b.UpdatedAt
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (b *BulkTransferRequest) GetCurrency() string {
	if b == nil || b.Currency == nil {
		return ""
	}
	return *b.Currency
}

// GetSource returns the Source field if it's non-nil, zero value otherwise.
func (b *BulkTransferRequest) GetSource() string {
	if b == nil || b.Source == nil {
		return ""
	}
	return *b.Source
}

// GetBvn returns the Bvn field if it's non-nil, zero value otherwise.
func (b *BvnData) GetBvn() string {
	if b == nil || b.Bvn == nil {
		return ""
	}
	return *b.Bvn
}

// GetDob returns the Dob field if it's non-nil, zero value otherwise.
func (b *BvnData) GetDob() string {
	if b == nil || b.Dob == nil {
		return ""
	}
	return *b.Dob
}

// GetFirstName returns the FirstName field if it's non-nil, zero value otherwise.
func (b *BvnData) GetFirstName() string {
	if b == nil || b.FirstName == nil {
		return ""
	}
	return *b.FirstName
}

// GetLastName returns the LastName field if it's non-nil, zero value otherwise.
func (b *BvnData) GetLastName() string {
	if b == nil || b.LastName == nil {
		return ""
	}
	return *b.LastName
}

// GetMobile returns the Mobile field if it's non-nil, zero value otherwise.
func (b *BvnData) GetMobile() string {
	if b == nil || b.Mobile == nil {
		return ""
	}
	return *b.Mobile
}

// GetCVV returns the CVV field if it's non-nil, zero value otherwise.
func (c *Card) GetCVV() string {
	if c == nil || c.CVV == nil {
		return ""
	}
	return *c.CVV
}

// GetExpiryMonth returns the ExpiryMonth field if it's non-nil, zero value otherwise.
func (c *Card) GetExpiryMonth() string {
	if c == nil || c.ExpiryMonth == nil {
		return ""
	}
	return *c.ExpiryMonth
}

// GetExpiryYear returns the ExpiryYear field if it's non-nil, zero value otherwise.
func (c *Card) GetExpiryYear() string {
	if c == nil || c.ExpiryYear == nil {
		return ""
	}
	return *c.ExpiryYear
}

// GetNumber returns the Number field if it's non-nil, zero value otherwise.
func (c *Card) GetNumber() string {
	if c == nil || c.Number == nil {
		return ""
	}
	return *c.Number
}

// GetAuthorizationCode returns the AuthorizationCode field if it's non-nil, zero value otherwise.
func (c *ChargeRequest) GetAuthorizationCode() string {
	if c == nil || c.AuthorizationCode == nil {
		return ""
	}
	return *c.AuthorizationCode
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (c *ChargeRequest) GetEmail() string {
	if c == nil || c.Email == nil {
		return ""
	}
	return *c.Email
}

// GetPin returns the Pin field if it's non-nil, zero value otherwise.
func (c *ChargeRequest) GetPin() string {
	if c == nil || c.Pin == nil {
		return ""
	}
	return *c.Pin
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (c *Customer) GetCreatedAt() time.Time {
	if c == nil || c.CreatedAt == nil {
		return time.Time{}
	}
	return *c.CreatedAt
}

// GetCustomerCode returns the CustomerCode field if it's non-nil, zero value otherwise.
func (c *Customer) GetCustomerCode() string {
	if c == nil || c.CustomerCode == nil {
		return ""
	}
	return *c.CustomerCode
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (c *Customer) GetDomain() string {
	if c == nil || c.Domain == nil {
		return ""
	}
	return *c.Domain
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (c *Customer) GetEmail() string {
	if c == nil || c.Email == nil {
		return ""
	}
	return *c.Email
}

// GetFirstName returns the FirstName field if it's non-nil, zero value otherwise.
func (c *Customer) GetFirstName() string {
	if c == nil || c.FirstName == nil {
		return ""
	}
	return *c.FirstName
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (c *Customer) GetId() int {
	if c == nil || c.Id == nil {
		return 0
	}
	return *c.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (c *Customer) GetIntegration() int {
	if c == nil || c.Integration == nil {
		return 0
	}
	return *c.Integration
}

// GetLastName returns the LastName field if it's non-nil, zero value otherwise.
func (c *Customer) GetLastName() string {
	if c == nil || c.LastName == nil {
		return ""
	}
	return *c.LastName
}

// GetPhone returns the Phone field if it's non-nil, zero value otherwise.
func (c *Customer) GetPhone() string {
	if c == nil || c.Phone == nil {
		return ""
	}
	return *c.Phone
}

// GetRiskAction returns the RiskAction field if it's non-nil, zero value otherwise.
func (c *Customer) GetRiskAction() string {
	if c == nil || c.RiskAction == nil {
		return ""
	}
	return *c.RiskAction
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (c *Customer) GetUpdatedAt() time.Time {
	if c == nil || c.UpdatedAt == nil {
		return time.Time{}
	}
	return *c.UpdatedAt
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (c *CustomerRequest) GetEmail() string {
	if c == nil || c.Email == nil {
		return ""
	}
	return *c.Email
}

// GetFirstName returns the FirstName field if it's non-nil, zero value otherwise.
func (c *CustomerRequest) GetFirstName() string {
	if c == nil || c.FirstName == nil {
		return ""
	}
	return *c.FirstName
}

// GetLastName returns the LastName field if it's non-nil, zero value otherwise.
func (c *CustomerRequest) GetLastName() string {
	if c == nil || c.LastName == nil {
		return ""
	}
	return *c.LastName
}

// GetPhone returns the Phone field if it's non-nil, zero value otherwise.
func (c *CustomerRequest) GetPhone() string {
	if c == nil || c.Phone == nil {
		return ""
	}
	return *c.Phone
}

// GetDisplayName returns the DisplayName field if it's non-nil, zero value otherwise.
func (c *CustomFields) GetDisplayName() string {
	if c == nil || c.DisplayName == nil {
		return ""
	}
	return *c.DisplayName
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (c *CustomFields) GetValue() string {
	if c == nil || c.Value == nil {
		return ""
	}
	return *c.Value
}

// GetVariableName returns the VariableName field if it's non-nil, zero value otherwise.
func (c *CustomFields) GetVariableName() string {
	if c == nil || c.VariableName == nil {
		return ""
	}
	return *c.VariableName
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (e *ExportRequest) GetCurrency() string {
	if e == nil || e.Currency == nil {
		return ""
	}
	return *e.Currency
}

// GetFrom returns the From field if it's non-nil, zero value otherwise.
func (e *ExportRequest) GetFrom() time.Time {
	if e == nil || e.From == nil {
		return time.Time{}
	}
	return *e.From
}

// GetSettled returns the Settled field if it's non-nil, zero value otherwise.
func (e *ExportRequest) GetSettled() bool {
	if e == nil || e.Settled == nil {
		return false
	}
	return *e.Settled
}

// GetSettlement returns the Settlement field if it's non-nil, zero value otherwise.
func (e *ExportRequest) GetSettlement() string {
	if e == nil || e.Settlement == nil {
		return ""
	}
	return *e.Settlement
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (e *ExportRequest) GetStatus() string {
	if e == nil || e.Status == nil {
		return ""
	}
	return *e.Status
}

// GetTo returns the To field if it's non-nil, zero value otherwise.
func (e *ExportRequest) GetTo() time.Time {
	if e == nil || e.To == nil {
		return time.Time{}
	}
	return *e.To
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (f *FieldByCurrency) GetAmount() string {
	if f == nil || f.Amount == nil {
		return ""
	}
	return *f.Amount
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (f *FieldByCurrency) GetCurrency() string {
	if f == nil || f.Currency == nil {
		return ""
	}
	return *f.Currency
}

// GetOTP returns the OTP field if it's non-nil, zero value otherwise.
func (f *FinalizeTransferRequest) GetOTP() string {
	if f == nil || f.OTP == nil {
		return ""
	}
	return *f.OTP
}

// GetTransferCode returns the TransferCode field if it's non-nil, zero value otherwise.
func (f *FinalizeTransferRequest) GetTransferCode() string {
	if f == nil || f.TransferCode == nil {
		return ""
	}
	return *f.TransferCode
}

// GetMessage returns the Message field if it's non-nil, zero value otherwise.
func (h *History) GetMessage() string {
	if h == nil || h.Message == nil {
		return ""
	}
	return *h.Message
}

// GetTime returns the Time field if it's non-nil, zero value otherwise.
func (h *History) GetTime() string {
	if h == nil || h.Time == nil {
		return ""
	}
	return *h.Time
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (h *History) GetType() string {
	if h == nil || h.Type == nil {
		return ""
	}
	return *h.Type
}

// GetChannel returns the Channel field if it's non-nil, zero value otherwise.
func (l *Log) GetChannel() string {
	if l == nil || l.Channel == nil {
		return ""
	}
	return *l.Channel
}

// GetMobile returns the Mobile field if it's non-nil, zero value otherwise.
func (l *Log) GetMobile() bool {
	if l == nil || l.Mobile == nil {
		return false
	}
	return *l.Mobile
}

// GetSuccess returns the Success field if it's non-nil, zero value otherwise.
func (l *Log) GetSuccess() bool {
	if l == nil || l.Success == nil {
		return false
	}
	return *l.Success
}

// GetMessage returns the Message field if it's non-nil, zero value otherwise.
func (m *Message) GetMessage() string {
	if m == nil || m.Message == nil {
		return ""
	}
	return *m.Message
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (m *Message) GetStatus() bool {
	if m == nil || m.Status == nil {
		return false
	}
	return *m.Status
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (o *ListOptions) GetAmount() string {
	if o == nil || o.Amount == nil {
		return ""
	}
	return *o.Amount
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (o *ListOptions) GetCurrency() string {
	if o == nil || o.Currency == nil {
		return ""
	}
	return *o.Currency
}

// GetFrom returns the From field if it's non-nil, zero value otherwise.
func (o *ListOptions) GetFrom() time.Time {
	if o == nil || o.From == nil {
		return time.Time{}
	}
	return *o.From
}

// GetPaymentPage returns the PaymentPage field if it's non-nil, zero value otherwise.
func (o *ListOptions) GetPaymentPage() int {
	if o == nil || o.PaymentPage == nil {
		return 0
	}
	return *o.PaymentPage
}

// GetSettled returns the Settled field if it's non-nil, zero value otherwise.
func (o *ListOptions) GetSettled() bool {
	if o == nil || o.Settled == nil {
		return false
	}
	return *o.Settled
}

// GetSettlement returns the Settlement field if it's non-nil, zero value otherwise.
func (o *ListOptions) GetSettlement() int {
	if o == nil || o.Settlement == nil {
		return 0
	}
	return *o.Settlement
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (o *ListOptions) GetStatus() string {
	if o == nil || o.Status == nil {
		return ""
	}
	return *o.Status
}

// GetSubaccount returns the Subaccount field if it's non-nil, zero value otherwise.
func (o *ListOptions) GetSubaccount() string {
	if o == nil || o.Subaccount == nil {
		return ""
	}
	return *o.Subaccount
}

// GetTimeout returns the Timeout field if it's non-nil, zero value otherwise.
func (o *ListOptions) GetTimeout() int {
	if o == nil || o.Timeout == nil {
		return 0
	}
	return *o.Timeout
}

// GetTo returns the To field if it's non-nil, zero value otherwise.
func (o *ListOptions) GetTo() time.Time {
	if o == nil || o.To == nil {
		return time.Time{}
	}
	return *o.To
}

// GetOTP returns the OTP field if it's non-nil, zero value otherwise.
func (o *OTPRequest) GetOTP() string {
	if o == nil || o.OTP == nil {
		return ""
	}
	return *o.OTP
}

// GetReference returns the Reference field if it's non-nil, zero value otherwise.
func (o *OTPRequest) GetReference() string {
	if o == nil || o.Reference == nil {
		return ""
	}
	return *o.Reference
}

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (p *Page) GetActive() bool {
	if p == nil || p.Active == nil {
		return false
	}
	return *p.Active
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (p *Page) GetAmount() int {
	if p == nil || p.Amount == nil {
		return 0
	}
	return *p.Amount
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (p *Page) GetCreatedAt() time.Time {
	if p == nil || p.CreatedAt == nil {
		return time.Time{}
	}
	return *p.CreatedAt
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (p *Page) GetCurrency() string {
	if p == nil || p.Currency == nil {
		return ""
	}
	return *p.Currency
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (p *Page) GetDescription() string {
	if p == nil || p.Description == nil {
		return ""
	}
	return *p.Description
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (p *Page) GetDomain() string {
	if p == nil || p.Domain == nil {
		return ""
	}
	return *p.Domain
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (p *Page) GetId() int {
	if p == nil || p.Id == nil {
		return 0
	}
	return *p.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (p *Page) GetIntegration() int {
	if p == nil || p.Integration == nil {
		return 0
	}
	return *p.Integration
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (p *Page) GetName() string {
	if p == nil || p.Name == nil {
		return ""
	}
	return *p.Name
}

// GetPlan returns the Plan field if it's non-nil, zero value otherwise.
func (p *Page) GetPlan() int {
	if p == nil || p.Plan == nil {
		return 0
	}
	return *p.Plan
}

// GetRedirectUrl returns the RedirectUrl field if it's non-nil, zero value otherwise.
func (p *Page) GetRedirectUrl() string {
	if p == nil || p.RedirectUrl == nil {
		return ""
	}
	return *p.RedirectUrl
}

// GetSlug returns the Slug field if it's non-nil, zero value otherwise.
func (p *Page) GetSlug() string {
	if p == nil || p.Slug == nil {
		return ""
	}
	return *p.Slug
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (p *Page) GetUpdatedAt() time.Time {
	if p == nil || p.UpdatedAt == nil {
		return time.Time{}
	}
	return *p.UpdatedAt
}

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (p *PageRequest) GetActive() bool {
	if p == nil || p.Active == nil {
		return false
	}
	return *p.Active
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (p *PageRequest) GetAmount() int {
	if p == nil || p.Amount == nil {
		return 0
	}
	return *p.Amount
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (p *PageRequest) GetCurrency() string {
	if p == nil || p.Currency == nil {
		return ""
	}
	return *p.Currency
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (p *PageRequest) GetDescription() string {
	if p == nil || p.Description == nil {
		return ""
	}
	return *p.Description
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (p *PageRequest) GetId() int {
	if p == nil || p.Id == nil {
		return 0
	}
	return *p.Id
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (p *PageRequest) GetName() string {
	if p == nil || p.Name == nil {
		return ""
	}
	return *p.Name
}

// GetRedirectUrl returns the RedirectUrl field if it's non-nil, zero value otherwise.
func (p *PageRequest) GetRedirectUrl() string {
	if p == nil || p.RedirectUrl == nil {
		return ""
	}
	return *p.RedirectUrl
}

// GetSlug returns the Slug field if it's non-nil, zero value otherwise.
func (p *PageRequest) GetSlug() string {
	if p == nil || p.Slug == nil {
		return ""
	}
	return *p.Slug
}

// GetPaymentSessionTimeout returns the PaymentSessionTimeout field if it's non-nil, zero value otherwise.
func (p *PaymentSession) GetPaymentSessionTimeout() int {
	if p == nil || p.PaymentSessionTimeout == nil {
		return 0
	}
	return *p.PaymentSessionTimeout
}

// GetOTP returns the OTP field if it's non-nil, zero value otherwise.
func (p *PhoneRequest) GetOTP() string {
	if p == nil || p.OTP == nil {
		return ""
	}
	return *p.OTP
}

// GetReference returns the Reference field if it's non-nil, zero value otherwise.
func (p *PhoneRequest) GetReference() string {
	if p == nil || p.Reference == nil {
		return ""
	}
	return *p.Reference
}

// GetPin returns the Pin field if it's non-nil, zero value otherwise.
func (p *PinRequest) GetPin() string {
	if p == nil || p.Pin == nil {
		return ""
	}
	return *p.Pin
}

// GetReference returns the Reference field if it's non-nil, zero value otherwise.
func (p *PinRequest) GetReference() string {
	if p == nil || p.Reference == nil {
		return ""
	}
	return *p.Reference
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (p *Plan) GetAmount() int {
	if p == nil || p.Amount == nil {
		return 0
	}
	return *p.Amount
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (p *Plan) GetCreatedAt() time.Time {
	if p == nil || p.CreatedAt == nil {
		return time.Time{}
	}
	return *p.CreatedAt
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (p *Plan) GetCurrency() string {
	if p == nil || p.Currency == nil {
		return ""
	}
	return *p.Currency
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (p *Plan) GetDescription() string {
	if p == nil || p.Description == nil {
		return ""
	}
	return *p.Description
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (p *Plan) GetDomain() string {
	if p == nil || p.Domain == nil {
		return ""
	}
	return *p.Domain
}

// GetHostedPage returns the HostedPage field if it's non-nil, zero value otherwise.
func (p *Plan) GetHostedPage() bool {
	if p == nil || p.HostedPage == nil {
		return false
	}
	return *p.HostedPage
}

// GetHostedPageSummary returns the HostedPageSummary field if it's non-nil, zero value otherwise.
func (p *Plan) GetHostedPageSummary() string {
	if p == nil || p.HostedPageSummary == nil {
		return ""
	}
	return *p.HostedPageSummary
}

// GetHostedPageURL returns the HostedPageURL field if it's non-nil, zero value otherwise.
func (p *Plan) GetHostedPageURL() string {
	if p == nil || p.HostedPageURL == nil {
		return ""
	}
	return *p.HostedPageURL
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (p *Plan) GetId() int {
	if p == nil || p.Id == nil {
		return 0
	}
	return *p.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (p *Plan) GetIntegration() int {
	if p == nil || p.Integration == nil {
		return 0
	}
	return *p.Integration
}

// GetInterval returns the Interval field if it's non-nil, zero value otherwise.
func (p *Plan) GetInterval() string {
	if p == nil || p.Interval == nil {
		return ""
	}
	return *p.Interval
}

// GetInvoiceLimit returns the InvoiceLimit field if it's non-nil, zero value otherwise.
func (p *Plan) GetInvoiceLimit() string {
	if p == nil || p.InvoiceLimit == nil {
		return ""
	}
	return *p.InvoiceLimit
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (p *Plan) GetName() string {
	if p == nil || p.Name == nil {
		return ""
	}
	return *p.Name
}

// GetPlanCode returns the PlanCode field if it's non-nil, zero value otherwise.
func (p *Plan) GetPlanCode() string {
	if p == nil || p.PlanCode == nil {
		return ""
	}
	return *p.PlanCode
}

// GetSendInvoices returns the SendInvoices field if it's non-nil, zero value otherwise.
func (p *Plan) GetSendInvoices() bool {
	if p == nil || p.SendInvoices == nil {
		return false
	}
	return *p.SendInvoices
}

// GetSendSms returns the SendSms field if it's non-nil, zero value otherwise.
func (p *Plan) GetSendSms() bool {
	if p == nil || p.SendSms == nil {
		return false
	}
	return *p.SendSms
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (p *Plan) GetUpdatedAt() time.Time {
	if p == nil || p.UpdatedAt == nil {
		return time.Time{}
	}
	return *p.UpdatedAt
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (p *PlanRequest) GetAmount() int {
	if p == nil || p.Amount == nil {
		return 0
	}
	return *p.Amount
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (p *PlanRequest) GetCurrency() string {
	if p == nil || p.Currency == nil {
		return ""
	}
	return *p.Currency
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (p *PlanRequest) GetDescription() string {
	if p == nil || p.Description == nil {
		return ""
	}
	return *p.Description
}

// GetInterval returns the Interval field if it's non-nil, zero value otherwise.
func (p *PlanRequest) GetInterval() string {
	if p == nil || p.Interval == nil {
		return ""
	}
	return *p.Interval
}

// GetInvoiceLimit returns the InvoiceLimit field if it's non-nil, zero value otherwise.
func (p *PlanRequest) GetInvoiceLimit() string {
	if p == nil || p.InvoiceLimit == nil {
		return ""
	}
	return *p.InvoiceLimit
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (p *PlanRequest) GetName() string {
	if p == nil || p.Name == nil {
		return ""
	}
	return *p.Name
}

// GetSendInvoices returns the SendInvoices field if it's non-nil, zero value otherwise.
func (p *PlanRequest) GetSendInvoices() bool {
	if p == nil || p.SendInvoices == nil {
		return false
	}
	return *p.SendInvoices
}

// GetSendSms returns the SendSms field if it's non-nil, zero value otherwise.
func (p *PlanRequest) GetSendSms() bool {
	if p == nil || p.SendSms == nil {
		return false
	}
	return *p.SendSms
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetAmount() int {
	if p == nil || p.Amount == nil {
		return 0
	}
	return *p.Amount
}

// GetAuthorization returns the Authorization field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetAuthorization() int {
	if p == nil || p.Authorization == nil {
		return 0
	}
	return *p.Authorization
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetCreatedAt() time.Time {
	if p == nil || p.CreatedAt == nil {
		return time.Time{}
	}
	return *p.CreatedAt
}

// GetCronExpression returns the CronExpression field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetCronExpression() string {
	if p == nil || p.CronExpression == nil {
		return ""
	}
	return *p.CronExpression
}

// GetCustomer returns the Customer field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetCustomer() int {
	if p == nil || p.Customer == nil {
		return 0
	}
	return *p.Customer
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetDomain() string {
	if p == nil || p.Domain == nil {
		return ""
	}
	return *p.Domain
}

// GetEasyCronId returns the EasyCronId field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetEasyCronId() int {
	if p == nil || p.EasyCronId == nil {
		return 0
	}
	return *p.EasyCronId
}

// GetEmailToken returns the EmailToken field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetEmailToken() string {
	if p == nil || p.EmailToken == nil {
		return ""
	}
	return *p.EmailToken
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetId() int {
	if p == nil || p.Id == nil {
		return 0
	}
	return *p.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetIntegration() int {
	if p == nil || p.Integration == nil {
		return 0
	}
	return *p.Integration
}

// GetNextPaymentDate returns the NextPaymentDate field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetNextPaymentDate() time.Time {
	if p == nil || p.NextPaymentDate == nil {
		return time.Time{}
	}
	return *p.NextPaymentDate
}

// GetPlan returns the Plan field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetPlan() int {
	if p == nil || p.Plan == nil {
		return 0
	}
	return *p.Plan
}

// GetQuantity returns the Quantity field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetQuantity() int {
	if p == nil || p.Quantity == nil {
		return 0
	}
	return *p.Quantity
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetStatus() string {
	if p == nil || p.Status == nil {
		return ""
	}
	return *p.Status
}

// GetSubscriptionCode returns the SubscriptionCode field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetSubscriptionCode() string {
	if p == nil || p.SubscriptionCode == nil {
		return ""
	}
	return *p.SubscriptionCode
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (p *PlanSubscription) GetUpdatedAt() time.Time {
	if p == nil || p.UpdatedAt == nil {
		return time.Time{}
	}
	return *p.UpdatedAt
}

// GetReauthorizationUrl returns the ReauthorizationUrl field if it's non-nil, zero value otherwise.
func (r *Reauthorization) GetReauthorizationUrl() string {
	if r == nil || r.ReauthorizationUrl == nil {
		return ""
	}
	return *r.ReauthorizationUrl
}

// GetReference returns the Reference field if it's non-nil, zero value otherwise.
func (r *Reauthorization) GetReference() string {
	if r == nil || r.Reference == nil {
		return ""
	}
	return *r.Reference
}

// GetCustomerCode returns the CustomerCode field if it's non-nil, zero value otherwise.
func (r *RiskActionPayload) GetCustomerCode() string {
	if r == nil || r.CustomerCode == nil {
		return ""
	}
	return *r.CustomerCode
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (s *Settlement) GetCreatedAt() time.Time {
	if s == nil || s.CreatedAt == nil {
		return time.Time{}
	}
	return *s.CreatedAt
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (s *Settlement) GetDomain() string {
	if s == nil || s.Domain == nil {
		return ""
	}
	return *s.Domain
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (s *Settlement) GetId() int {
	if s == nil || s.Id == nil {
		return 0
	}
	return *s.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (s *Settlement) GetIntegration() int {
	if s == nil || s.Integration == nil {
		return 0
	}
	return *s.Integration
}

// GetSettledDate returns the SettledDate field if it's non-nil, zero value otherwise.
func (s *Settlement) GetSettledDate() time.Time {
	if s == nil || s.SettledDate == nil {
		return time.Time{}
	}
	return *s.SettledDate
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (s *Settlement) GetStatus() string {
	if s == nil || s.Status == nil {
		return ""
	}
	return *s.Status
}

// GetTotalAmount returns the TotalAmount field if it's non-nil, zero value otherwise.
func (s *Settlement) GetTotalAmount() int {
	if s == nil || s.TotalAmount == nil {
		return 0
	}
	return *s.TotalAmount
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (s *Settlement) GetUpdatedAt() time.Time {
	if s == nil || s.UpdatedAt == nil {
		return time.Time{}
	}
	return *s.UpdatedAt
}

// GetAccountNumber returns the AccountNumber field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetAccountNumber() string {
	if s == nil || s.AccountNumber == nil {
		return ""
	}
	return *s.AccountNumber
}

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetActive() bool {
	if s == nil || s.Active == nil {
		return false
	}
	return *s.Active
}

// GetBusinessName returns the BusinessName field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetBusinessName() string {
	if s == nil || s.BusinessName == nil {
		return ""
	}
	return *s.BusinessName
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetCreatedAt() time.Time {
	if s == nil || s.CreatedAt == nil {
		return time.Time{}
	}
	return *s.CreatedAt
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetDescription() string {
	if s == nil || s.Description == nil {
		return ""
	}
	return *s.Description
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetDomain() string {
	if s == nil || s.Domain == nil {
		return ""
	}
	return *s.Domain
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetId() int {
	if s == nil || s.Id == nil {
		return 0
	}
	return *s.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetIntegration() int {
	if s == nil || s.Integration == nil {
		return 0
	}
	return *s.Integration
}

// GetIsVerified returns the IsVerified field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetIsVerified() bool {
	if s == nil || s.IsVerified == nil {
		return false
	}
	return *s.IsVerified
}

// GetMigrate returns the Migrate field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetMigrate() bool {
	if s == nil || s.Migrate == nil {
		return false
	}
	return *s.Migrate
}

// GetPrimaryContactEmail returns the PrimaryContactEmail field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetPrimaryContactEmail() string {
	if s == nil || s.PrimaryContactEmail == nil {
		return ""
	}
	return *s.PrimaryContactEmail
}

// GetPrimaryContactName returns the PrimaryContactName field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetPrimaryContactName() string {
	if s == nil || s.PrimaryContactName == nil {
		return ""
	}
	return *s.PrimaryContactName
}

// GetPrimaryContactPhone returns the PrimaryContactPhone field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetPrimaryContactPhone() string {
	if s == nil || s.PrimaryContactPhone == nil {
		return ""
	}
	return *s.PrimaryContactPhone
}

// GetSettlementBank returns the SettlementBank field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetSettlementBank() string {
	if s == nil || s.SettlementBank == nil {
		return ""
	}
	return *s.SettlementBank
}

// GetSettlementSchedule returns the SettlementSchedule field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetSettlementSchedule() string {
	if s == nil || s.SettlementSchedule == nil {
		return ""
	}
	return *s.SettlementSchedule
}

// GetSubaccountCode returns the SubaccountCode field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetSubaccountCode() string {
	if s == nil || s.SubaccountCode == nil {
		return ""
	}
	return *s.SubaccountCode
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (s *Subaccount) GetUpdatedAt() time.Time {
	if s == nil || s.UpdatedAt == nil {
		return time.Time{}
	}
	return *s.UpdatedAt
}

// GetAccountNumber returns the AccountNumber field if it's non-nil, zero value otherwise.
func (s *SubaccountRequest) GetAccountNumber() string {
	if s == nil || s.AccountNumber == nil {
		return ""
	}
	return *s.AccountNumber
}

// GetBusinessName returns the BusinessName field if it's non-nil, zero value otherwise.
func (s *SubaccountRequest) GetBusinessName() string {
	if s == nil || s.BusinessName == nil {
		return ""
	}
	return *s.BusinessName
}

// GetPrimaryContactEmail returns the PrimaryContactEmail field if it's non-nil, zero value otherwise.
func (s *SubaccountRequest) GetPrimaryContactEmail() string {
	if s == nil || s.PrimaryContactEmail == nil {
		return ""
	}
	return *s.PrimaryContactEmail
}

// GetPrimaryContactName returns the PrimaryContactName field if it's non-nil, zero value otherwise.
func (s *SubaccountRequest) GetPrimaryContactName() string {
	if s == nil || s.PrimaryContactName == nil {
		return ""
	}
	return *s.PrimaryContactName
}

// GetPrimaryContactPhone returns the PrimaryContactPhone field if it's non-nil, zero value otherwise.
func (s *SubaccountRequest) GetPrimaryContactPhone() string {
	if s == nil || s.PrimaryContactPhone == nil {
		return ""
	}
	return *s.PrimaryContactPhone
}

// GetSettlementBank returns the SettlementBank field if it's non-nil, zero value otherwise.
func (s *SubaccountRequest) GetSettlementBank() string {
	if s == nil || s.SettlementBank == nil {
		return ""
	}
	return *s.SettlementBank
}

// GetSettlementSchedule returns the SettlementSchedule field if it's non-nil, zero value otherwise.
func (s *SubaccountRequest) GetSettlementSchedule() string {
	if s == nil || s.SettlementSchedule == nil {
		return ""
	}
	return *s.SettlementSchedule
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (s *Subscription) GetAmount() int {
	if s == nil || s.Amount == nil {
		return 0
	}
	return *s.Amount
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (s *Subscription) GetCreatedAt() time.Time {
	if s == nil || s.CreatedAt == nil {
		return time.Time{}
	}
	return *s.CreatedAt
}

// GetCronExpression returns the CronExpression field if it's non-nil, zero value otherwise.
func (s *Subscription) GetCronExpression() string {
	if s == nil || s.CronExpression == nil {
		return ""
	}
	return *s.CronExpression
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (s *Subscription) GetDomain() string {
	if s == nil || s.Domain == nil {
		return ""
	}
	return *s.Domain
}

// GetEasyCronId returns the EasyCronId field if it's non-nil, zero value otherwise.
func (s *Subscription) GetEasyCronId() int {
	if s == nil || s.EasyCronId == nil {
		return 0
	}
	return *s.EasyCronId
}

// GetEmailToken returns the EmailToken field if it's non-nil, zero value otherwise.
func (s *Subscription) GetEmailToken() string {
	if s == nil || s.EmailToken == nil {
		return ""
	}
	return *s.EmailToken
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (s *Subscription) GetId() int {
	if s == nil || s.Id == nil {
		return 0
	}
	return *s.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (s *Subscription) GetIntegration() int {
	if s == nil || s.Integration == nil {
		return 0
	}
	return *s.Integration
}

// GetNextPaymentDate returns the NextPaymentDate field if it's non-nil, zero value otherwise.
func (s *Subscription) GetNextPaymentDate() time.Time {
	if s == nil || s.NextPaymentDate == nil {
		return time.Time{}
	}
	return *s.NextPaymentDate
}

// GetOpenInvoice returns the OpenInvoice field if it's non-nil, zero value otherwise.
func (s *Subscription) GetOpenInvoice() string {
	if s == nil || s.OpenInvoice == nil {
		return ""
	}
	return *s.OpenInvoice
}

// GetQuantity returns the Quantity field if it's non-nil, zero value otherwise.
func (s *Subscription) GetQuantity() int {
	if s == nil || s.Quantity == nil {
		return 0
	}
	return *s.Quantity
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (s *Subscription) GetStatus() string {
	if s == nil || s.Status == nil {
		return ""
	}
	return *s.Status
}

// GetSubscriptionCode returns the SubscriptionCode field if it's non-nil, zero value otherwise.
func (s *Subscription) GetSubscriptionCode() string {
	if s == nil || s.SubscriptionCode == nil {
		return ""
	}
	return *s.SubscriptionCode
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (s *Subscription) GetUpdatedAt() time.Time {
	if s == nil || s.UpdatedAt == nil {
		return time.Time{}
	}
	return *s.UpdatedAt
}

// GetAuthorization returns the Authorization field if it's non-nil, zero value otherwise.
func (s *SubscriptionRequest) GetAuthorization() string {
	if s == nil || s.Authorization == nil {
		return ""
	}
	return *s.Authorization
}

// GetCode returns the Code field if it's non-nil, zero value otherwise.
func (s *SubscriptionRequest) GetCode() string {
	if s == nil || s.Code == nil {
		return ""
	}
	return *s.Code
}

// GetCustomer returns the Customer field if it's non-nil, zero value otherwise.
func (s *SubscriptionRequest) GetCustomer() string {
	if s == nil || s.Customer == nil {
		return ""
	}
	return *s.Customer
}

// GetPlan returns the Plan field if it's non-nil, zero value otherwise.
func (s *SubscriptionRequest) GetPlan() string {
	if s == nil || s.Plan == nil {
		return ""
	}
	return *s.Plan
}

// GetStartDate returns the StartDate field if it's non-nil, zero value otherwise.
func (s *SubscriptionRequest) GetStartDate() time.Time {
	if s == nil || s.StartDate == nil {
		return time.Time{}
	}
	return *s.StartDate
}

// GetToken returns the Token field if it's non-nil, zero value otherwise.
func (s *SubscriptionRequest) GetToken() string {
	if s == nil || s.Token == nil {
		return ""
	}
	return *s.Token
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetAmount() int {
	if s == nil || s.Amount == nil {
		return 0
	}
	return *s.Amount
}

// GetAuthorization returns the Authorization field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetAuthorization() int {
	if s == nil || s.Authorization == nil {
		return 0
	}
	return *s.Authorization
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetCreatedAt() time.Time {
	if s == nil || s.CreatedAt == nil {
		return time.Time{}
	}
	return *s.CreatedAt
}

// GetCustomer returns the Customer field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetCustomer() int {
	if s == nil || s.Customer == nil {
		return 0
	}
	return *s.Customer
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetDomain() string {
	if s == nil || s.Domain == nil {
		return ""
	}
	return *s.Domain
}

// GetEmailToken returns the EmailToken field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetEmailToken() string {
	if s == nil || s.EmailToken == nil {
		return ""
	}
	return *s.EmailToken
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetId() int {
	if s == nil || s.Id == nil {
		return 0
	}
	return *s.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetIntegration() int {
	if s == nil || s.Integration == nil {
		return 0
	}
	return *s.Integration
}

// GetPlan returns the Plan field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetPlan() int {
	if s == nil || s.Plan == nil {
		return 0
	}
	return *s.Plan
}

// GetQuantity returns the Quantity field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetQuantity() int {
	if s == nil || s.Quantity == nil {
		return 0
	}
	return *s.Quantity
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetStatus() string {
	if s == nil || s.Status == nil {
		return ""
	}
	return *s.Status
}

// GetSubscriptionCode returns the SubscriptionCode field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetSubscriptionCode() string {
	if s == nil || s.SubscriptionCode == nil {
		return ""
	}
	return *s.SubscriptionCode
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (s *SubscriptionResponse) GetUpdatedAt() time.Time {
	if s == nil || s.UpdatedAt == nil {
		return time.Time{}
	}
	return *s.UpdatedAt
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (t *Transaction) GetAmount() int {
	if t == nil || t.Amount == nil {
		return 0
	}
	return *t.Amount
}

// GetChannel returns the Channel field if it's non-nil, zero value otherwise.
func (t *Transaction) GetChannel() string {
	if t == nil || t.Channel == nil {
		return ""
	}
	return *t.Channel
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (t *Transaction) GetCreatedAt() time.Time {
	if t == nil || t.CreatedAt == nil {
		return time.Time{}
	}
	return *t.CreatedAt
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (t *Transaction) GetCurrency() string {
	if t == nil || t.Currency == nil {
		return ""
	}
	return *t.Currency
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (t *Transaction) GetDomain() string {
	if t == nil || t.Domain == nil {
		return ""
	}
	return *t.Domain
}

// GetFees returns the Fees field if it's non-nil, zero value otherwise.
func (t *Transaction) GetFees() int {
	if t == nil || t.Fees == nil {
		return 0
	}
	return *t.Fees
}

// GetFeesSplit returns the FeesSplit field if it's non-nil, zero value otherwise.
func (t *Transaction) GetFeesSplit() int {
	if t == nil || t.FeesSplit == nil {
		return 0
	}
	return *t.FeesSplit
}

// GetGatewayResponse returns the GatewayResponse field if it's non-nil, zero value otherwise.
func (t *Transaction) GetGatewayResponse() string {
	if t == nil || t.GatewayResponse == nil {
		return ""
	}
	return *t.GatewayResponse
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (t *Transaction) GetId() int {
	if t == nil || t.Id == nil {
		return 0
	}
	return *t.Id
}

// GetIpAddress returns the IpAddress field if it's non-nil, zero value otherwise.
func (t *Transaction) GetIpAddress() string {
	if t == nil || t.IpAddress == nil {
		return ""
	}
	return *t.IpAddress
}

// GetMessage returns the Message field if it's non-nil, zero value otherwise.
func (t *Transaction) GetMessage() string {
	if t == nil || t.Message == nil {
		return ""
	}
	return *t.Message
}

// GetPaidAt returns the PaidAt field if it's non-nil, zero value otherwise.
func (t *Transaction) GetPaidAt() time.Time {
	if t == nil || t.PaidAt == nil {
		return time.Time{}
	}
	return *t.PaidAt
}

// GetReference returns the Reference field if it's non-nil, zero value otherwise.
func (t *Transaction) GetReference() string {
	if t == nil || t.Reference == nil {
		return ""
	}
	return *t.Reference
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (t *Transaction) GetStatus() string {
	if t == nil || t.Status == nil {
		return ""
	}
	return *t.Status
}

// GetTransactionDate returns the TransactionDate field if it's non-nil, zero value otherwise.
func (t *Transaction) GetTransactionDate() time.Time {
	if t == nil || t.TransactionDate == nil {
		return time.Time{}
	}
	return *t.TransactionDate
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (t *TransactionRequest) GetAmount() string {
	if t == nil || t.Amount == nil {
		return ""
	}
	return *t.Amount
}

// GetAuthorizationCode returns the AuthorizationCode field if it's non-nil, zero value otherwise.
func (t *TransactionRequest) GetAuthorizationCode() string {
	if t == nil || t.AuthorizationCode == nil {
		return ""
	}
	return *t.AuthorizationCode
}

// GetBearer returns the Bearer field if it's non-nil, zero value otherwise.
func (t *TransactionRequest) GetBearer() string {
	if t == nil || t.Bearer == nil {
		return ""
	}
	return *t.Bearer
}

// GetCallbackUrl returns the CallbackUrl field if it's non-nil, zero value otherwise.
func (t *TransactionRequest) GetCallbackUrl() string {
	if t == nil || t.CallbackUrl == nil {
		return ""
	}
	return *t.CallbackUrl
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (t *TransactionRequest) GetCurrency() string {
	if t == nil || t.Currency == nil {
		return ""
	}
	return *t.Currency
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (t *TransactionRequest) GetEmail() string {
	if t == nil || t.Email == nil {
		return ""
	}
	return *t.Email
}

// GetPlan returns the Plan field if it's non-nil, zero value otherwise.
func (t *TransactionRequest) GetPlan() string {
	if t == nil || t.Plan == nil {
		return ""
	}
	return *t.Plan
}

// GetReference returns the Reference field if it's non-nil, zero value otherwise.
func (t *TransactionRequest) GetReference() string {
	if t == nil || t.Reference == nil {
		return ""
	}
	return *t.Reference
}

// GetSubaccount returns the Subaccount field if it's non-nil, zero value otherwise.
func (t *TransactionRequest) GetSubaccount() string {
	if t == nil || t.Subaccount == nil {
		return ""
	}
	return *t.Subaccount
}

// GetAttempts returns the Attempts field if it's non-nil, zero value otherwise.
func (t *TransactionTimeline) GetAttempts() int {
	if t == nil || t.Attempts == nil {
		return 0
	}
	return *t.Attempts
}

// GetAuthentication returns the Authentication field if it's non-nil, zero value otherwise.
func (t *TransactionTimeline) GetAuthentication() string {
	if t == nil || t.Authentication == nil {
		return ""
	}
	return *t.Authentication
}

// GetChannel returns the Channel field if it's non-nil, zero value otherwise.
func (t *TransactionTimeline) GetChannel() string {
	if t == nil || t.Channel == nil {
		return ""
	}
	return *t.Channel
}

// GetErrors returns the Errors field if it's non-nil, zero value otherwise.
func (t *TransactionTimeline) GetErrors() int {
	if t == nil || t.Errors == nil {
		return 0
	}
	return *t.Errors
}

// GetMobile returns the Mobile field if it's non-nil, zero value otherwise.
func (t *TransactionTimeline) GetMobile() bool {
	if t == nil || t.Mobile == nil {
		return false
	}
	return *t.Mobile
}

// GetSuccess returns the Success field if it's non-nil, zero value otherwise.
func (t *TransactionTimeline) GetSuccess() bool {
	if t == nil || t.Success == nil {
		return false
	}
	return *t.Success
}

// GetTimeSpent returns the TimeSpent field if it's non-nil, zero value otherwise.
func (t *TransactionTimeline) GetTimeSpent() int {
	if t == nil || t.TimeSpent == nil {
		return 0
	}
	return *t.TimeSpent
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (t *Transfer) GetAmount() int {
	if t == nil || t.Amount == nil {
		return 0
	}
	return *t.Amount
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (t *Transfer) GetCreatedAt() time.Time {
	if t == nil || t.CreatedAt == nil {
		return time.Time{}
	}
	return *t.CreatedAt
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (t *Transfer) GetCurrency() string {
	if t == nil || t.Currency == nil {
		return ""
	}
	return *t.Currency
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (t *Transfer) GetDomain() string {
	if t == nil || t.Domain == nil {
		return ""
	}
	return *t.Domain
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (t *Transfer) GetId() int {
	if t == nil || t.Id == nil {
		return 0
	}
	return *t.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (t *Transfer) GetIntegration() int {
	if t == nil || t.Integration == nil {
		return 0
	}
	return *t.Integration
}

// GetReason returns the Reason field if it's non-nil, zero value otherwise.
func (t *Transfer) GetReason() string {
	if t == nil || t.Reason == nil {
		return ""
	}
	return *t.Reason
}

// GetSource returns the Source field if it's non-nil, zero value otherwise.
func (t *Transfer) GetSource() string {
	if t == nil || t.Source == nil {
		return ""
	}
	return *t.Source
}

// GetSourceDetails returns the SourceDetails field if it's non-nil, zero value otherwise.
func (t *Transfer) GetSourceDetails() string {
	if t == nil || t.SourceDetails == nil {
		return ""
	}
	return *t.SourceDetails
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (t *Transfer) GetStatus() string {
	if t == nil || t.Status == nil {
		return ""
	}
	return *t.Status
}

// GetTransferCode returns the TransferCode field if it's non-nil, zero value otherwise.
func (t *Transfer) GetTransferCode() string {
	if t == nil || t.TransferCode == nil {
		return ""
	}
	return *t.TransferCode
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (t *Transfer) GetUpdatedAt() time.Time {
	if t == nil || t.UpdatedAt == nil {
		return time.Time{}
	}
	return *t.UpdatedAt
}

// GetActive returns the Active field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetActive() bool {
	if t == nil || t.Active == nil {
		return false
	}
	return *t.Active
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetCreatedAt() time.Time {
	if t == nil || t.CreatedAt == nil {
		return time.Time{}
	}
	return *t.CreatedAt
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetCurrency() string {
	if t == nil || t.Currency == nil {
		return ""
	}
	return *t.Currency
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetDescription() string {
	if t == nil || t.Description == nil {
		return ""
	}
	return *t.Description
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetDomain() string {
	if t == nil || t.Domain == nil {
		return ""
	}
	return *t.Domain
}

// GetId returns the Id field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetId() int {
	if t == nil || t.Id == nil {
		return 0
	}
	return *t.Id
}

// GetIntegration returns the Integration field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetIntegration() int {
	if t == nil || t.Integration == nil {
		return 0
	}
	return *t.Integration
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetName() string {
	if t == nil || t.Name == nil {
		return ""
	}
	return *t.Name
}

// GetRecipientCode returns the RecipientCode field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetRecipientCode() string {
	if t == nil || t.RecipientCode == nil {
		return ""
	}
	return *t.RecipientCode
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetType() string {
	if t == nil || t.Type == nil {
		return ""
	}
	return *t.Type
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (t *TransferRecipient) GetUpdatedAt() time.Time {
	if t == nil || t.UpdatedAt == nil {
		return time.Time{}
	}
	return *t.UpdatedAt
}

// GetAccountName returns the AccountName field if it's non-nil, zero value otherwise.
func (t *TransferRecipientDetails) GetAccountName() string {
	if t == nil || t.AccountName == nil {
		return ""
	}
	return *t.AccountName
}

// GetAccountNumber returns the AccountNumber field if it's non-nil, zero value otherwise.
func (t *TransferRecipientDetails) GetAccountNumber() string {
	if t == nil || t.AccountNumber == nil {
		return ""
	}
	return *t.AccountNumber
}

// GetBankCode returns the BankCode field if it's non-nil, zero value otherwise.
func (t *TransferRecipientDetails) GetBankCode() string {
	if t == nil || t.BankCode == nil {
		return ""
	}
	return *t.BankCode
}

// GetBankName returns the BankName field if it's non-nil, zero value otherwise.
func (t *TransferRecipientDetails) GetBankName() string {
	if t == nil || t.BankName == nil {
		return ""
	}
	return *t.BankName
}

// GetAccountNumber returns the AccountNumber field if it's non-nil, zero value otherwise.
func (t *TransferRecipientRequest) GetAccountNumber() string {
	if t == nil || t.AccountNumber == nil {
		return ""
	}
	return *t.AccountNumber
}

// GetBankCode returns the BankCode field if it's non-nil, zero value otherwise.
func (t *TransferRecipientRequest) GetBankCode() string {
	if t == nil || t.BankCode == nil {
		return ""
	}
	return *t.BankCode
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (t *TransferRecipientRequest) GetCurrency() string {
	if t == nil || t.Currency == nil {
		return ""
	}
	return *t.Currency
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (t *TransferRecipientRequest) GetDescription() string {
	if t == nil || t.Description == nil {
		return ""
	}
	return *t.Description
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (t *TransferRecipientRequest) GetName() string {
	if t == nil || t.Name == nil {
		return ""
	}
	return *t.Name
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (t *TransferRecipientRequest) GetType() string {
	if t == nil || t.Type == nil {
		return ""
	}
	return *t.Type
}

// GetAmount returns the Amount field if it's non-nil, zero value otherwise.
func (t *TransferRequest) GetAmount() int {
	if t == nil || t.Amount == nil {
		return 0
	}
	return *t.Amount
}

// GetCurrency returns the Currency field if it's non-nil, zero value otherwise.
func (t *TransferRequest) GetCurrency() string {
	if t == nil || t.Currency == nil {
		return ""
	}
	return *t.Currency
}

// GetReason returns the Reason field if it's non-nil, zero value otherwise.
func (t *TransferRequest) GetReason() string {
	if t == nil || t.Reason == nil {
		return ""
	}
	return *t.Reason
}

// GetRecipient returns the Recipient field if it's non-nil, zero value otherwise.
func (t *TransferRequest) GetRecipient() string {
	if t == nil || t.Recipient == nil {
		return ""
	}
	return *t.Recipient
}

// GetSource returns the Source field if it's non-nil, zero value otherwise.
func (t *TransferRequest) GetSource() string {
	if t == nil || t.Source == nil {
		return ""
	}
	return *t.Source
}

// GetTransferCode returns the TransferCode field if it's non-nil, zero value otherwise.
func (t *TransferRequest) GetTransferCode() string {
	if t == nil || t.TransferCode == nil {
		return ""
	}
	return *t.TransferCode
}
